# Generated by Django 4.1.3 on 2022-11-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_platos_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='platos',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='platos',
            name='precio',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='platos',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
